/*
    This file was generated by doing the following steps:

    1. git clone https://github.com/katahiromz/DOSSTUB
    2. compile DOSSTUB1.ASM with NASM
    3. Copy DOSHEAD.BIN at the beginning of the compiled NASM output
    4. Run file2c on the generated file
    5. Adjust accordingly

    DOS STUBS ARE RELEASED UNDER MIT LICENSE, SEE https://github.com/katahiromz/DOSSTUB/blob/master/LICENSE.txt
*/
#include <stdlib.h>
const char dosstub[] = "\
MZ`\000\001\000\000\000\004\000\000\000\377\377\000\000\270\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\016\037\272\016\000\264\t\315!\270\001L\315!This program cannot be run in DOS mode.\r\n\
\044";
const size_t dosstub_len = sizeof(dosstub) - 1;
